import {chromium} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
fs.mkdirSync('../output/demo',{recursive:true});
const fixture=(name)=>fs.readFileSync(path.join('..','sample-data',name),'utf-8');
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'../output/demo',size:{width:1440,height:1000}}});
const page=await context.newPage();
await page.goto('http://127.0.0.1:8000');
await page.getByText('Or paste resume text',{exact:true}).click();
await page.getByLabel('Base resume text',{exact:true}).fill(fixture('candidate-base.md'));
await page.getByRole('button',{name:'Save resume text',exact:true}).click();
await page.getByLabel('Add supporting evidence').setInputFiles({name:'project-evidence.md',mimeType:'text/plain',buffer:Buffer.from(fixture('project-evidence.md'))});
if(await page.getByRole('button',{name:'Edit header',exact:true}).count())await page.getByRole('button',{name:'Edit header',exact:true}).click();
await page.getByLabel('Full name',{exact:true}).fill('Mira Rao');
await page.getByLabel('Contact line',{exact:true}).fill('mira@example.com');
await page.getByLabel('Role title',{exact:true}).fill('Junior Frontend Developer');
await page.getByLabel('Company',{exact:true}).fill('CedarWorks Labs');
await page.getByLabel('Job description Required',{exact:true}).fill(fixture('job-frontend.md'));
await page.getByRole('button',{name:'Save job description',exact:true}).click();
await page.locator('.kb-details summary').click();
await page.getByPlaceholder('Relevant company or product facts').fill(fixture('company-knowledge.md'));
await page.getByRole('button',{name:'Save company knowledge',exact:true}).click();
await page.waitForTimeout(1600);
await page.getByRole('button',{name:'Review my evidence',exact:true}).click();
await page.locator('.source-link').first().click();await page.waitForTimeout(1800);await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Approve supported excerpts'}).click();
await page.getByRole('button',{name:'Build my application'}).click();
await page.getByRole('heading',{name:'Your application package is ready.'}).waitFor({timeout:30000});
await page.waitForTimeout(1800);
await page.getByRole('button',{name:'Claim sources',exact:true}).click();await page.waitForTimeout(1500);
await page.getByRole('button',{name:'Changes',exact:true}).click();await page.waitForTimeout(1300);
await page.getByRole('button',{name:'Inspect activity log'}).click();await page.waitForTimeout(1800);
const video=page.video();await context.close();await video.saveAs('../output/demo/mock-workflow.webm');await browser.close();
fs.writeFileSync('../output/demo/RECORDING.md','# Local offline recording\n\nThis silent browser recording shows an actual offline run with data entered manually through the UI (no preloaded sample endpoint), not live Gemini. The visible engine badge and real activity log identify the mode. Recorded '+new Date().toISOString()+'. No replay is presented as current execution.\n');
console.log('Recorded actual offline workflow: output/demo/mock-workflow.webm');
