import {chromium} from 'playwright';
import fs from 'node:fs';
fs.mkdirSync('../output/demo',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'../output/demo',size:{width:1440,height:1000}}});
const page=await context.newPage();
await page.goto('http://127.0.0.1:8000');
await page.getByRole('button',{name:'Load fictional sample',exact:true}).waitFor();
await page.waitForTimeout(1600);
await page.getByRole('button',{name:'Load fictional sample',exact:true}).click();
await page.locator('.source-link').first().click();await page.waitForTimeout(1800);await page.keyboard.press('Escape');
await page.getByRole('button',{name:'Approve supported excerpts'}).click();
await page.getByRole('button',{name:'Build my resume'}).click();
await page.getByRole('heading',{name:'A resume you can stand behind.'}).waitFor({timeout:30000});
await page.waitForTimeout(1800);
await page.getByRole('button',{name:'Claim sources',exact:true}).click();await page.waitForTimeout(1500);
await page.getByRole('button',{name:'Changes',exact:true}).click();await page.waitForTimeout(1300);
await page.getByRole('button',{name:'Inspect activity log'}).click();await page.waitForTimeout(1800);
const video=page.video();await context.close();await video.saveAs('../output/demo/mock-workflow.webm');await browser.close();
fs.writeFileSync('../output/demo/RECORDING.md','# Local offline recording\n\nThis silent browser recording shows an actual fictional mock-provider run, not live Gemini. The visible mode badge and real activity log identify the mode. Recorded '+new Date().toISOString()+'. No replay is presented as current execution.\n');
console.log('Recorded actual offline workflow: output/demo/mock-workflow.webm');
