"""Shared skill vocabulary for the explicit offline (mock) matcher.

These canonical skill names extend the small built-in technology mapping used by
``terms()`` in providers.py so role coverage reflects real-world resumes instead
of only the fictional-fixture stack. Matching stays strictly excerpt-grounded:
a skill counts only when its literal name (word-bounded, case-insensitive)
appears in the original source text. No synonyms, abbreviations or aliases are
invented -- e.g. ``k8s`` does not match ``Kubernetes`` and ``ML`` does not match
``Machine Learning``. Multi-word skills require the full contiguous phrase, and
single-word skills use word boundaries, so ``Java`` never matches ``JavaScript``
and ``SQL`` never matches ``MySQL``.

This changes *recognition*, not truthfulness: every match still requires the
candidate's own eligible excerpt to contain the skill, and uncertain claims
still cannot pass the release gate.
"""

import re

# Canonical skill names supplied by the user (deduplicated case-insensitively).
SKILLS = (
    "A/B Testing",
    "ABP Style",
    "Active Listening",
    "Adaptability",
    "Administrative Support",
    "Advanced Functions",
    "Agile Methodologies",
    "Analytical Skills",
    "Analytical Thinking",
    "AP Style",
    "AWS",
    "AWS Lambda",
    "Account Management",
    "Accountability",
    "Accounting",
    "Accounts Payable",
    "Accounts Receivable",
    "Active Engagement",
    "Adaptation to Technology",
    "Adobe Creative Suite",
    "Adobe Illustrator",
    "Adobe Photoshop",
    "Adobe XD",
    "Advanced Data Analysis",
    "Agile Project Management",
    "Analytical Modeling",
    "Analytical Problem Solving",
    "Annual Budgeting",
    "App Development",
    "Artificial Intelligence",
    "Asset Management",
    "Attention to Detail",
    "Audience Engagement",
    "Audit Preparation",
    "Automated Content Development",
    "Automation",
    "Azure",
    "Azure Functions",
    "B2B Marketing",
    "BI Developer",
    "BI Tools",
    "Budget Management",
    "Budget Monitoring",
    "Budgeting",
    "Business Analysis",
    "Business Consulting",
    "Business Development",
    "Business Intelligence",
    "Business Strategy",
    "CRM",
    "CRM Systems",
    "C++ Expertise",
    "CAD",
    "Cash Flow Management",
    "Cash Management",
    "Change Management",
    "Chart Analysis",
    "Cloud Architect",
    "Cloud Computing",
    "Cloud Engineer",
    "Cloud Infrastructure",
    "Cloud Management",
    "Cloud Ops",
    "Coaching",
    "Code Review",
    "Collaboration",
    "Communication",
    "Competitor Analysis",
    "Compliance",
    "Computational Thinking",
    "Computer Installation",
    "Computer Proficiency",
    "Conceptual Skills",
    "Conflict Resolution",
    "Containerization",
    "Content Creation",
    "Content Management",
    "Content Marketing",
    "Copy Editing",
    "Copywriting",
    "Corporate Finance",
    "Corporate Licensing",
    "Cost Accounting",
    "Cost Analysis",
    "Cost Control",
    "Cost Management",
    "Cost Reduction",
    "Creative Activities",
    "Creative Problem Solving",
    "Creative Thinking",
    "Creativity",
    "Critical Decision Making",
    "Critical Reading",
    "Critical Thinking",
    "Customer Acquisition",
    "Customer Analytics",
    "Customer Experience",
    "Customer Relationship Management",
    "Customer Retention",
    "Customer Segmentation",
    "Customer Service",
    "Cybersecurity",
    "Dashboard Creation",
    "Data Analysis",
    "Data Analytics",
    "Data Assessment",
    "Data Engineer",
    "Data Interpretation",
    "Data Management",
    "Data Mining",
    "Data Modeling",
    "Data Science",
    "Data Structuring",
    "Data Visualization",
    "Data Warehousing",
    "Database Management",
    "Decision Making",
    "Deep Learning",
    "Delegation",
    "Design Patterns",
    "Design Thinking",
    "DevOps",
    "Digital Forensics",
    "Digital Marketing",
    "Digital Merchandising",
    "Diplomacy",
    "Docker",
    "Document Analysis",
    "Domain Knowledge",
    "E-commerce Optimization",
    "Edge Computing",
    "Editorial Style Guides",
    "Electrical Circuit Design",
    "Email Marketing",
    "Emotional Intelligence",
    "Empathy",
    "Employee Engagement",
    "Enterprise Sales",
    "ERP Systems",
    "ESG Reporting",
    "Excel",
    "Execution Planning",
    "Executive Presentations",
    "Experience Design",
    "Facebook Ads",
    "Financial Analysis",
    "Financial Forecasting",
    "Financial Modeling",
    "Financial Planning",
    "Financial Reporting",
    "Financial Statement Analysis",
    "Financial Systems",
    "Firebase",
    "Firewalls",
    "Fiscal Year Budgeting",
    "Forecasting",
    "Foreign Language",
    "Front-End Development",
    "Full Stack Development",
    "GAAP",
    "GDPR",
    "Git",
    "Goal Setting",
    "Google Ads",
    "Google Analytics",
    "Google Cloud",
    "Graphic Design",
    "Growth Hacking",
    "Hard Skills",
    "Hardware",
    "Heatmaps",
    "Hotjar",
    "HTML",
    "HR Management",
    "HRIS",
    "Human Resources",
    "Hybrid Cloud",
    "IBM Cloud",
    "IFRS",
    "Illustrator",
    "Incident Response",
    "Income Statement Analysis",
    "Influencer Marketing",
    "Information Architecture",
    "Innovation",
    "Instagram Marketing",
    "Instructional Design",
    "Interpersonal Skills",
    "Intrusion Detection",
    "Intrusion Prevention",
    "Investment Analysis",
    "Java",
    "JavaScript",
    "Jenkins",
    "Job Scheduling",
    "Jupyter Notebook",
    "Kubernetes",
    "Kotlin",
    "KPI Tracking",
    "Landing Page Optimization",
    "Laravel",
    "Leadership",
    "Lean Six Sigma",
    "Legal Compliance",
    "LinkedIn Marketing",
    "Linux",
    "Machine Learning",
    "Magento",
    "Mailchimp",
    "Market Research",
    "Marketing Analytics",
    "Marketing Automation",
    "Marketing Strategy",
    "Master Data Management",
    "Matplotlib",
    "Matlab",
    "Media Planning",
    "Mentoring",
    "Microsoft Azure",
    "Microsoft Clarity",
    "Microsoft Excel",
    "Microsoft Office",
    "Microsoft Power BI",
    "Microsoft SQL Server",
    "Microsoft Word",
    "Mixpanel",
    "Mobile App Development",
    "Mobile Development",
    "Mobile Marketing",
    "MongoDB",
    "Motion Graphics",
    "Motivation",
    "Multi-Tasking",
    "Multitasking",
    "MySQL",
    "NLP",
    "Negotiation",
    "Net Promoter Score",
    "Network Maintenance",
    "Network Protocols",
    "Network Security",
    "Networking",
    "Node.js",
    "NoSQL",
    "Numeracy",
    "Numerical Analysis",
    "Nursing",
    "Objective C",
    "Online Advertising",
    "Oracle",
    "Organizational Skills",
    "Outlook",
    "PaaS",
    "PHP",
    "PL SQL",
    "PMO",
    "PostgreSQL",
    "Power BI",
    "Predictive Analytics",
    "Predictive Modeling",
    "Presentation",
    "Presentation Skills",
    "Problem Analysis",
    "Problem Solving",
    "Product Design",
    "Product Management",
    "Product Marketing",
    "Product Strategy",
    "Program Debugging",
    "Project Budgeting",
    "Project Charter",
    "Project Closure",
    "Project Coordination",
    "Project Documentation",
    "Project Management",
    "Project Planning",
    "Project Scheduling",
    "Prompt Engineering",
    "Proofreading",
    "Prototyping",
    "Public Relations",
    "Public Speaking",
    "Python",
    "PyTorch",
    "Qlik Sense",
    "QlikView",
    "Qualitative Research",
    "Quantitative Analysis",
    "QuickBooks",
    "R Programming",
    "React",
    "React Native",
    "Redis",
    "Regulatory Compliance",
    "Relationship Building",
    "Reporting",
    "Requirements Gathering",
    "Research",
    "Resilience",
    "Resource Management",
    "Resource Planning",
    "Resourcefulness",
    "Responsiveness",
    "Retail Analytics",
    "Retrieval Augmented Generation",
    "Risk Analysis",
    "Risk Assessment",
    "Risk Management",
    "ROI Analysis",
    "Ruby",
    "Ruby on Rails",
    "SAP",
    "SAS",
    "SaaS",
    "Salesforce",
    "Salesforce Marketing Cloud",
    "Salesforce Sales Cloud",
    "Scikit-Learn",
    "Scrum",
    "Security Protocols",
    "Self-Motivation",
    "Semantic HTML",
    "SEO",
    "SEM",
    "SEM Rush",
    "SEO Tools",
    "Serverless Computing",
    "Sketch",
    "Slack",
    "Social Grace",
    "Social Influence",
    "Social Listening",
    "Social Media",
    "Social Media Analytics",
    "Social Media Management",
    "Software Development",
    "Software Engineering",
    "Software Testing",
    "Spark",
    "Speech Recognition",
    "Sprint Planning",
    "SQL",
    "SSH",
    "Stakeholder Communication",
    "Stakeholder Engagement",
    "Stakeholder Management",
    "Statistical Analysis",
    "Statistical Modeling",
    "Statistics",
    "Storytelling",
    "Strategic Marketing",
    "Strategic Partnerships",
    "Strategic Planning",
    "Strategic Thinking",
    "Strategy Development",
    "Supply Chain Management",
    "Supply Chain Optimization",
    "Swift",
    "SwiftUI",
    "Tableau",
    "Tally",
    "Team Collaboration",
    "Team Leadership",
    "Team Management",
    "Teamwork",
    "Technical Analysis",
    "Technical Documentation",
    "Technical Drawing",
    "Technical Leadership",
    "Technical Support",
    "Technical Writing",
    "Technical Writing Tools",
    "TensorFlow",
    "Test Driven Development",
    "Testing Frameworks",
    "Thought Leadership",
    "Time Management",
    "Time Series Analysis",
    "Tooltip",
    "Treasury Management",
    "Twitter Marketing",
    "TypeScript",
    "UI Design",
    "UX Design",
    "UX Research",
    "Unit Testing",
    "User Interviews",
    "User Research",
    "User Stories",
    "Valuation Techniques",
    "Variance Analysis",
    "Version Control",
    "Video Editing",
    "Video Marketing",
    "Virtual Private Networks",
    "Virtual Reality",
    "Virtualization",
    "Visual Basic",
    "Visual Studio",
    "Visualisation",
    "VMware",
    "Vue.js",
    "Vulnerability Assessment",
    "Web Analytics",
    "Web Design",
    "Web Development",
    "Wireshark",
    "WordPress",
    "Work Under Pressure",
    "Workflow Automation",
    "Workshop Facilitation",
    "Xamarin",
    "XML",
    "XPath",
    "Yii",
    "Zend Framework",
    "Zoom",
    "Account-Based Marketing",
    "Account-Based Selling",
    "Administration Management",
    "Agile Coaching",
    "Agile Facilitation",
    "Applicant Tracking System Management",
    "Application Support",
    "Asset Liability Management",
    "Audit Coordination",
    "Automation Strategy",
    "Balanced Scorecard Management",
    "Benchmarking Analysis",
    "Benefits Administration",
    "Blue Ocean Strategy",
    "Board Meeting Coordination",
    "Board Reporting",
    "Brand Communication",
    "Brand Management",
    "Brand Positioning",
    "Brand Strategy",
    "Business Case Development",
    "Business Continuity Planning",
    "Business Development Strategy",
    "Business Forecasting",
    "Business Intelligence Reporting",
    "Business Model Innovation",
    "Business Operations Management",
    "Business Performance Management",
    "Business Process Automation",
    "Business Process Improvement",
    "Business Process Mapping",
    "Business Process Reengineering",
    "Business Transformation",
    "Campus Hiring",
    "Capital Budgeting",
    "Capital Expenditure Planning",
    "Category Management",
    "Change Readiness Assessment",
    "Change Roadmapping",
    "Client Advisory",
    "Client Onboarding",
    "Client Relationship Management",
    "Coaching and Mentoring",
    "Cohort Analysis",
    "Commercial Negotiation",
    "Communication Strategy",
    "Compensation and Benefits Management",
    "Competition Mapping",
    "Compliance Auditing",
    "Compliance Documentation",
    "Consultative Selling",
    "Contract Lifecycle Management",
    "Contract Management",
    "Contract Negotiation",
    "Contribution Margin Analysis",
    "Conversion Funnel Optimization",
    "Conversion Rate Optimization",
    "Corporate Communications",
    "Corporate Governance",
    "Corporate Strategy",
    "Cost Benchmarking",
    "Cost of Quality Analysis",
    "Credit Risk Management",
    "Cross-Border Collaboration",
    "Cross-Cultural Communication",
    "Cross-Functional Leadership",
    "Cross-Functional Project Management",
    "Customer Delight Initiatives",
    "Customer Feedback Analysis",
    "Customer Journey Mapping",
    "Customer Lifetime Value Modeling",
    "Customer Onboarding",
    "Customer Satisfaction Analysis",
    "Customer Success Management",
    "Data Governance",
    "Data Lineage Documentation",
    "Data Privacy Management",
    "Data Quality Management",
    "Data-Driven Decision Making",
    "Deal Structuring",
    "Deliverables Management",
    "Design Operations",
    "Design System Management",
    "Digital Adoption Management",
    "Digital Campaign Management",
    "Digital Transformation",
    "Disaster Recovery Planning",
    "Dispute Resolution",
    "Diversity and Inclusion Initiatives",
    "Document Control",
    "Due Diligence",
    "E-Learning Development",
    "Employee Engagement Strategy",
    "Employee Grievance Handling",
    "Employee Lifecycle Management",
    "Employee Onboarding",
    "Employee Retention Strategy",
    "Employer Branding",
    "Engagement Strategy",
    "Enterprise Architecture",
    "Enterprise Risk Management",
    "Equity Research",
    "Escalation Management",
    "Event Management",
    "Executive Communication",
    "Executive Stakeholder Management",
    "Expense Management",
    "Facilitation Skills",
    "Feasibility Analysis",
    "Field Sales Management",
    "Financial Due Diligence",
    "Financial Governance",
    "Financial Policy Development",
    "Financial Process Improvement",
    "Forecast Accuracy Improvement",
    "Franchise Management",
    "Fundraising Support",
    "Gap Analysis",
    "Go-To-Market Strategy",
    "Grant Proposal Writing",
    "Greenfield Project Management",
    "HR Analytics",
    "HR Business Partnering",
    "HR Compliance",
    "HR Policy Development",
    "Ideation Workshops",
    "Impact Assessment",
    "Incentive Plan Design",
    "Incident Management",
    "Influencing Without Authority",
    "Information Design",
    "Information Governance",
    "Innovation Management",
    "Instructional Facilitation",
    "Integrated Marketing Communications",
    "Internal Audit Support",
    "Internal Communications",
    "Internal Controls Design",
    "International Business Development",
    "Interviewing Skills",
    "Investment Appraisal",
    "IT Asset Management",
    "IT Governance",
    "IT Service Management",
    "IT Strategy",
    "Job Evaluation",
    "Kaizen Facilitation",
    "Key Account Management",
    "Key Stakeholder Mapping",
    "Knowledge Management",
    "KPI Dashboarding",
    "Lead Generation",
    "Lead Nurturing",
    "Lead Qualification",
    "Learning and Development",
    "Legal Drafting Support",
    "Logistics Management",
    "Loss Prevention Strategy",
    "Mergers and Acquisitions Analysis",
    "Merchandise Planning",
    "Microservices Architecture",
    "Migration Planning",
    "MIS Reporting",
    "Motivational Speaking",
    "Multi-Channel Campaigns",
    "Multi-Project Coordination",
    "Multi-Stakeholder Management",
    "Negotiation Strategy",
    "OKR Management",
    "Onsite-Offshore Coordination",
    "Operating Model Design",
    "Operational Excellence",
    "Operational Planning",
    "Operations Management",
    "Opportunity Assessment",
    "Order Management",
    "Organizational Development",
    "Organizational Restructuring",
    "Outsourcing Management",
    "Partnership Development",
    "Partnership Management",
    "Payroll Administration",
    "Performance Appraisal Management",
    "Performance Improvement Planning",
    "Performance Marketing",
    "Performance Review Facilitation",
    "Pilot Project Management",
    "Pipeline Management",
    "Policy Compliance Monitoring",
    "Policy Development",
    "Portfolio Management",
    "Portfolio Prioritization",
    "Positioning Strategy",
    "Post-Merger Integration Support",
    "Presentation Design",
    "Pricing Analysis",
    "Pricing Strategy",
    "Process Audit",
    "Process Documentation",
    "Process Improvement",
    "Process Mapping",
    "Process Optimization",
    "Procurement Management",
    "Product Lifecycle Management",
    "Product Roadmapping",
    "Professional Networking",
    "Program Governance",
    "Program Management",
    "Project Portfolio Management",
    "Proposal Development",
    "Prospect Research",
    "Public Affairs",
    "Quality Assurance",
    "Quality Control",
    "Quality Management Systems",
    "Query Resolution",
    "Quota Management",
    "Real Estate Portfolio Management",
    "Reconciliation Management",
    "Recruitment Strategy",
    "Reference Checking",
    "Regulatory Documentation",
    "Regulatory Reporting",
    "Requirements Prioritization",
    "Research Proposal Writing",
    "Resource Allocation",
    "Resource Forecasting",
    "Resource Optimization",
    "Response to RFPs",
    "Retail Expansion Planning",
    "Revenue Assurance",
    "Revenue Management",
    "Revenue Operations",
    "Review Management",
    "Risk Control Design",
    "Route-to-Market Strategy",
    "Sales Enablement",
    "Sales Incentive Design",
    "Sales Negotiation",
    "Sales Operations",
    "Sales Pipeline Forecasting",
    "Sales Strategy",
    "Scenario Modeling",
    "Scheduling Management",
    "Scope Definition",
    "Scope Management",
    "Segment Reporting",
    "Sensitivity Analysis",
    "Service Blueprinting",
    "Service Delivery Management",
    "Service Level Management",
    "Shareholder Communication",
    "Situational Leadership",
    "Solution Architecture",
    "Solution Design",
    "Solution Selling",
    "Stakeholder Analysis",
    "Stakeholder Expectations Management",
    "Stakeholder Mapping",
    "Stakeholder Presentation",
    "Store Operations Supervision",
    "Strategic Account Planning",
    "Strategic Cost Management",
    "Strategic Sourcing",
    "Succession Planning",
    "Supply Planning",
    "Talent Acquisition",
    "Talent Management",
    "Target Setting",
    "Team Building",
    "Territory Management",
    "Test Strategy Development",
    "Third-Party Risk Management",
    "Thought Leadership Content",
    "Ticket Queue Management",
    "Timeboxing Techniques",
    "Training Delivery",
    "Training Evaluation",
    "Training Needs Analysis",
    "Transition Management",
    "Trend Analysis",
    "User Journey Mapping",
    "User Persona Development",
    "User Training",
    "Vendor Assessment",
    "Vendor Contract Management",
    "Vendor Management",
    "Vendor Performance Evaluation",
    "Venture Support Analysis",
    "Visual Merchandising",
    "Voice of Customer Analysis",
    "Warehouse Management",
    "Warranty Management",
    "Win-Loss Analysis",
    "Workforce Planning",
    "Workflow Design",
)


def _normalize(value):
    # Hyphens/underscores/slashes-adjacent spacing collapse so that
    # "Front-End" and "Front End" compare identically.
    return re.sub(r"\s+", " ", re.sub(r"[-_]+", " ", value.strip().lower()))


# Deduplicated, longest-first for deterministic matching and capping.
_UNIQUE = sorted({_normalize(skill) for skill in SKILLS if skill.strip()}, key=len, reverse=True)
_PATTERNS = [(skill, re.compile(r"(?<!\w)" + re.escape(skill) + r"(?!\w)")) for skill in _UNIQUE]


def skill_terms(text):
    """Return canonical vocabulary skills literally present in text.

    Conservative literal matching only: no stemming, synonyms or aliases.
    """
    normalized = _normalize(text or "")
    return [skill for skill, pattern in _PATTERNS if pattern.search(normalized)]
